config/routes.rb
Rails.application.routes.draw do

  resources :registerdapps do
  	resources :events
  end

  root 'welcome#index'
  get 'welcome/about'

  devise_for :users

  namespace :api, defaults: {format: :json} do
  	match '/events', to: 'events#preflight', via: [:options]
  	resources :events, only: [:create]
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :registerdapp
end

app/models/registerdapp.rb
class Registerdapp < ActiveRecord::Base
	belongs_to :user
	has_many :events
	
	validates :title,
			  uniqueness: { case_sensitive: false }
	validates :body, :format => URI::regexp(%w(http https))
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :confirmable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :registerdapps
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
	skip_before_action :verify_authenticity_token
	before_filter :set_access_control_headers

   def set_access_control_headers
     headers['Access-Control-Allow-Origin'] = '*'
     headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
     headers['Access-Control-Allow-Headers'] = 'Content-Type'
   end

	def create
		registered_application = RegisteredApplication.find_by(url: request.env['HTTP_ORIGIN'])
		
		if registered_application.save
			render json: @event, status: :created
		else
			render json: {errors: @event.errors}, status: :unprocessable_entity
		end
	end

	def preflight
    	head 200
  	end

	private
	   def event_params
	     params.require(:event).permit(:name)
	   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def require_sign_in
     unless current_user
       flash[:alert] = "You must be logged in to do that"
       redirect_to new_user_session_path
     end
   end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def show
  	@event = Event.find(params[:id])
  end

  def new
  	@registerdapp = Registerdapp.find(params[:registerdapp_id])
  	@event = Event.new
  end

  def edit
  	@event = Event.find(params[:id])
  end

  def create
  	 @registerdapp = Registerdapp.find(params[:registerdapp_id])
  	 @event = @registerdapp.events.build(event_params)

     if @event.save
      flash[:notice] = "Event was saved!"
      redirect_to [@registerdapp, @event]
     else
      flash[:alert] = "There was an error saving the Event!"
      redirect_to :new
     end
  end

  private
  def event_params
    params.require(:event).permit(:name)
  end
end

app/controllers/registerdapps_controller.rb
class RegisterdappsController < ApplicationController
  before_action :require_sign_in

  def index
    @registerdapps = Registerdapp.all
  end

  def show
    @registerdapp = Registerdapp.find(params[:id])
  end

  def new
    @registerdapp = Registerdapp.new
  end

  def edit
    @registerdapp = Registerdapp.find(params[:id])
  end

  def create
    @registerdapp = Registerdapp.new(registerdapps_params)

    if @registerdapp.save
       flash[:notice] = "registerdapplication was saved."
       redirect_to @registerdapp, notice: "Registerd application was saved successfully."
     else
       flash.now[:alert] = "There was an error saving the registerdapplication. Please try again."
       render :new
     end
  end

  def update
  end

  def destroy
    @registerdapp = Registerdapp.find(params[:id])

    if @registerdapp.destroy
      flash[:notice] = "\"#{@registerdapp.title}\" was deleted successfully."
      redirect_to action: :index
    else
      flash.now[:alert] = "There was an error deleting the registerdapplication."
      render :show
    end
  end

  private
   def registerdapps_params
     params.require(:registerdapp).permit(:title, :body)
   end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def form_group_tag(errors, &block)
     css_class = 'form-group'
     css_class << ' has-error' if errors.any?

     content_tag :div, capture(&block), class: css_class
   end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/registerdapps_helper.rb
module RegisterdappsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/edit.html.erb
<h1>Events#edit</h1>
<p>Find me in app/views/events/edit.html.erb</p>

app/views/events/new.html.erb
<h1>Event New</h1>

<%= form_for [@registerdapp, @event] do |f| %>
    <% if @event.errors.any? %>
      <div class="alert alert-danger">
        <h4><%= pluralize(@event.errors.count, "error") %>.</h4>
        <ul>
          <% @event.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form_group_tag(@event.errors[:name]) do %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control', placeholder: "Enter Event Name" %>
    <% end %>

    <%= f.submit "Save", class: 'btn btn-success' %>
<% end %>

app/views/events/show.html.erb
<h1>Events#show</h1>
<p>Find me in app/views/events/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Metrics</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
     <ul class="nav nav-tabs">
       <li><%= link_to "Home", root_path %></li>
       <li><%= link_to "Applications", registerdapps_path %></li>
       <li><%= link_to "About", welcome_about_path %></li>

       <div class="pull-right user-info">
        <% if current_user %>
                <div class="pull-right">
                  <%= link_to current_user.email, edit_user_registration_path %> ||
                  <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
                </div>
        <% else %>
              <%= link_to "Sign In", new_user_session_path %> or
              <%= link_to "Sign Up", new_user_registration_path %>
        <% end %>
       </div>
     </ul>

     <% if flash[:notice] %>
       <div class="alert alert-success">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:notice] %>
       </div>
      <% elsif flash[:alert] %>
       <div class="alert alert-warning">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:alert] %>
       </div>
     <% end %>

     <%= yield %>
   </div>
   <div style="height: 5em"></div>

</body>
</html>

app/views/registerdapps/_form.html.erb
<%= form_for registerdapp do |f| %>
    <% if registerdapp.errors.any? %>
      <div class="alert alert-danger">
        <h4><%= pluralize(registerdapp.errors.count, "error") %>.</h4>
        <ul>
          <% registerdapp.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form_group_tag(registerdapp.errors[:title]) do %>
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "Enter Application title" %>
    <% end %>

    <%= form_group_tag(registerdapp.errors[:body]) do %>
      <%= f.label :Url %>
      <%= f.text_area :body, rows: 1, class: 'form-control', placeholder: "Enter application url" %>
    <% end %>

    <%= f.submit "Save", class: 'btn btn-success' %>
<% end %>

app/views/registerdapps/edit.html.erb
<h1 class="col-md-8">Edit Application</h1>

<div class="col-md-8">
   <%= render partial: 'form', locals: { registerdapp: @registerdapp } %>
</div>

app/views/registerdapps/index.html.erb
<h1>Applications</h1>
<div style="margin-top:1.5em;">
    <%= link_to "New Application", new_registerdapp_path, class: 'btn btn-success' %>
</div>

<% @registerdapps.each do |app| %>
	<div class="media">
     	<div class="media-body">
   			<h4 class="media-heading">
     			<%= link_to app.title, registerdapp_path(app) %> <br />
     			<small>
	             	<%= app.events.count %> Events
	            </small>
   			</h4>
     	</div>
	</div>
<% end %>

app/views/registerdapps/new.html.erb
<h1 class="col-md-8">New Application</h1>

<div class="col-md-8">
   <%= render partial: 'form', locals: { registerdapp: @registerdapp } %>
</div>

app/views/registerdapps/show.html.erb
<h1> <%= @registerdapp.title %> </h1>
<%= pie_chart @registerdapp.events.group(:name).count %>
<%= line_chart @registerdapp.events.group_by_day(:created_at).count %>
<%= link_to "Edit Application", edit_registerdapp_path, class: 'btn btn-success' %>
<%= link_to "Delete Application", @registerdapp, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this?' } %>

 <div class="row">
   <div class="col-md-8">
     <p class="lead"><%= @registerdapp.body %></p>
     <% @registerdapp.events.each do |event| %>
       <div class="media">
         <div class="media-body">
           <h4 class="media-heading">
             <%= link_to event.name, registerdapp_event_path(@registerdapp, event) %>
           </h4>
         </div>
       </div>
     <% end %>
   </div>
   <div class="col-md-4">
     <% if current_user %>
       <div class="col-md-4">
         <%= link_to "New Event", new_registerdapp_event_path(@registerdapp), class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/welcome/about.html.erb
<h1>About</h1>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>